In [1]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm  # Progress bar
import dill

from Value import Value
from ValueTensor import ValueTensor, criterion
from Layer import initialization, Layer, OutputLayer
from model import FFNN

# Load Dataset

In [2]:
X, y = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False)
Y = np.eye(10)[y.astype(int)] # one hot encoding untuk output

In [3]:
# normalisasi value
# asumsi dataset tidak berubah
X_normalized = X / 255
Y_normalized = Y / 255

In [4]:
# ambil sebagian data set karena terlalu lama
n = 700

X_sliced = X_normalized[:n]
Y_sliced = Y_normalized[:n]

In [5]:
# split training and validation set
X_train, X_val, Y_train, Y_val = train_test_split(X_sliced, Y_sliced, test_size=1/7, random_state=42)

# Test save and load model

In [7]:
ModelSigmaSkibidi = FFNN(2, [3, 4, 5], 10, ["linear", "relu", "sigmoid", "softmax"], "mse", [("zero", -1, 1, 42, "he") for _ in range (4)])
ModelSigmaSkibidi.save_model("mokel.pkl")

Model saved to mokel.pkl


In [11]:
ModelHawkTuah = FFNN.load_model("mokel.pkl")
print(ModelHawkTuah.input_size)
print(ModelHawkTuah.hidden_size_array)
print(ModelHawkTuah.output_size)
print(ModelHawkTuah.num_neurons)
print(ModelHawkTuah.activation_function)
print(ModelHawkTuah.loss_function)
print(ModelHawkTuah.weight_init)
print(ModelHawkTuah.input_and_hidden_layers[0].weights)

Model loaded from mokel.pkl
2
[3 4 5]
10
[ 2  3  4  5 10]
['linear', 'relu', 'sigmoid', 'softmax']
mse
[('zero', -1, 1, 42, 'he'), ('zero', -1, 1, 42, 'he'), ('zero', -1, 1, 42, 'he'), ('zero', -1, 1, 42, 'he')]
ValueTensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]])
